let pColor1 = document.getElementById("p1")
let pColor2 = document.getElementById("p2")
let pColor3 = document.getElementById("p3")
let pColor4 = document.getElementById("p4")
let pColor5 = document.getElementById("p5")

pColor1.style.color = "brown";
pColor2.style.color = "brown";
pColor3.style.color = "brown";
pColor4.style.color = "brown";
pColor5.style.color = "brown";
pColor1.style.width = 70 + "%" ;
pColor2.style.width = 50 + "%";
pColor3.style.width = 30 + "%";
pColor4.style.width = 100 + "%";
pColor5.style.width = 45 + "%";
pColor1.style.animation = "animScale";
pColor1.style.animationDuration = "10s";
pColor5.innerText = "Ceci est un nouveau texte";

let bgSpan1 = document.getElementById("span1")
let bgSpan2 = document.getElementById("span2")
let bgSpan3 = document.getElementById("span3")
let bgSpan4 = document.getElementById("span4")
let bgSpan5 = document.getElementById("span5")
let bgSpan6 = document.getElementById("span6")
let bgSpan7 = document.getElementById("span7")
let bgSpan8 = document.getElementById("span8")
let bgSpan9 = document.getElementById("span9")
let bgSpan10 = document.getElementById("span10")

bgSpan1.style.backgroundColor = "lightgreen";
bgSpan2.style.backgroundColor = "lightgreen";
bgSpan3.style.backgroundColor = "lightgreen";
bgSpan4.style.backgroundColor = "lightgreen";
bgSpan5.style.backgroundColor = "lightgreen";
bgSpan6.style.backgroundColor = "lightgreen";
bgSpan7.style.backgroundColor = "lightgreen";
bgSpan8.style.backgroundColor = "lightgreen";
bgSpan9.style.backgroundColor = "lightgreen";
bgSpan10.style.backgroundColor = "lightgreen";
bgSpan1.style.display = "block";
bgSpan2.style.display = "block";
bgSpan3.style.display = "block";
bgSpan4.style.display = "block";
bgSpan5.style.display = "block";
bgSpan6.style.display = "block";
bgSpan7.style.display = "block";
bgSpan8.style.display = "block";
bgSpan9.style.display = "block";
bgSpan10.style.display = "block";
bgSpan1.dir = "rtl"
bgSpan2.dir = "rtl";
bgSpan3.dir = "rtl";
bgSpan4.dir = "rtl";
bgSpan5.dir = "rtl";
bgSpan6.dir = "rtl";
bgSpan7.dir = "rtl";
bgSpan8.dir = "rtl";
bgSpan9.dir = "rtl";
bgSpan10.dir = "rtl";

let lien1 = document.getElementById("lien1");
let lien2 = document.getElementById("lien2");
let lien3 = document.getElementById("lien3");
let lien4 = document.getElementById("lien4");
let lien5 = document.getElementById("lien5");

lien1.innerText = "lien 1";
lien2.innerText = "lien 2";
lien3.innerText = "lien 3";
lien4.innerText = "lien 4";
lien5.innerText = "lien 5";
